### ISSUE TITLE
Cant find WSDL classes

### ISSUE THREAD

**Issue by andrescolodrero** [Microsoft/CRM-Performance-Toolkit#14]
Hi,
Im starting with this toolkit and i found this problem when i opened the project.
[Failure] Could not find file 'C:\Temp\CRM\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\WSDL\RelatedInformation.cs'

**Comment by jeffreyzhzhang** [comment]
Hi, can you check if there are any wsdl files in this folder - C:\Temp\CRM\CRMToolkit \Setup\WSDL\WSDL? If there are no wsdl files in that folder, can you try to open this url in your web browser - http[s]://ServerName/OrganizationName/XRMServices/2011/OrganizationData.svc?

**Comment by andrescolodrero** [comment]
Hi,
the .cs files are not in the zip file i get from github.

the link you show it doenst work, i have this

XRMServices/2011/Discovery.svc

**Comment by jeffreyzhzhang** [comment]
Can you please let me know how you set up the toolkit? Did you run ToolkitSetup.ps1?  If not, please follow the instructions in \CRMToolkit\Setup \Readme.txt to set up the toolkit first.

All the files in \CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\WSDL are generated in the run time during the toolkit setup.

If the link didn’t work for you, you might have issues with your CRM deployment. Are you working with anyone from Microsoft?

**Comment by andrescolodrero** [comment]
OK, now im having this problem.

I put all the dll in CrmLibs

.\ToolkitSetup.ps1 -AdminName (crm admin and SQL admin) -adminPassword passs -domainName mydomain -crmServerName crm2015 -sqlServerName mysSQLserver  -orgName CRMTEST -configSku Onprem -release CRM2015 -crmSdkBinDir  "C:\Temp\CRM\SDK\Bin" -ssl $true

After run:
Generage proxy for RelatedInformation
Running command - C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\wsdl.exe /n:RelatedInformation C:\Temp\CRM\CRMToolkit\Setup\WSDL\WSDL\RelatedInformation.wsdl /out:C
:\Temp\CRM\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\WSDL
C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\wsdl.exe /n:RelatedInformation C:\Temp\CRM\CRMToolkit\Setup\WSDL\WSDL\RelatedInformation.wsdl /out:C:\Temp\CRM\CRMTool
kit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\WSDL failed

IM having problem  downloading the WSDL 

"No Microsoft Dynamics CRM : No Microsoft Dynamics CRM user exists with the specified domain name and user ID"

The user has access to CRM organization and SQL Server,  but i will ask to my CRM partner why this is happeniing

**Comment by andrescolodrero** [comment]
Hi,
i found all the issues... i could not download the cs classes, and now i have the project ready to build

**Comment by rajeessh** [comment]
Hi All,
I am trying to run performance tool kit 2013 onpremise

when i run the following commands in power shell as admin

Upon execution of - ToolkitSetup.ps1 -adminName: -adminPassword:<CRM Administrator > -domainName: -crmServerName: -sqlServerName -orgName: -configSku: -release -crmSdkBinDir -crmSDKReservedDllPath -outlookDllsPath

a wsdl folder is created but inside its empty
C:\Users\crm.users\Desktop\xxxcrm\crmtkit\CRMToolkit\Setup\WSDL\WSDL

and throws following error

CRMToolkit\Setup\WSDL\WSDL onprem xxxchennai.local
The remote server returned an error: (404) Not Found.

Error: There was an error processing 'file:///C:/Users/crm.users/Desktop/xxxcrm/crmtkit/CRMToolkit/Setup/WSDL/WSDL/Relat
edInformation.wsdl'.
- There was an error downloading 'file:///C:/Users/crm.users/Desktop/xxxcrm/crmtkit/CRMToolkit/Setup/WSDL/WSDL/Related
Information.wsdl'.
- Could not find file 'C:\Users\crm.users\Desktop\xxxcrm\crmtkit\CRMToolkit\Setup\WSDL\WSDL\RelatedInformation.wsdl'.
- Could not find file 'C:\Users\crm.users\Desktop\xxxcrm\crmtkit\CRMToolkit\Setup\WSDL\WSDL\RelatedInformation.wsdl'

Its saying RelatedInformation.wsdl is not found - and its not creating automatically inside the folder - please guide where i went wrong

Regards,
Rajesh

**Comment by rajeessh** [comment]
@andrescolodrero  @jeffreyzhzhang 

Hi All,
I am trying to run performance tool kit 2013 onpremise

when i run the following commands in power shell as admin

Upon execution of - ToolkitSetup.ps1 -adminName: -adminPassword: -domainName: -crmServerName: -sqlServerName -orgName: -configSku: -release -crmSdkBinDir -crmSDKReservedDllPath -outlookDllsPath

a wsdl folder is created but inside its empty
C:\Users\crm.users\Desktop\xxxcrm\crmtkit\CRMToolkit\Setup\WSDL\WSDL

and throws following error

CRMToolkit\Setup\WSDL\WSDL onprem xxxchennai.local
The remote server returned an error: (404) Not Found.

Error: There was an error processing 'file:///C:/Users/crm.users/Desktop/xxxcrm/crmtkit/CRMToolkit/Setup/WSDL/WSDL/Relat
edInformation.wsdl'.

There was an error downloading 'file:///C:/Users/crm.users/Desktop/xxxcrm/crmtkit/CRMToolkit/Setup/WSDL/WSDL/Related
Information.wsdl'.
Could not find file 'C:\Users\crm.users\Desktop\xxxcrm\crmtkit\CRMToolkit\Setup\WSDL\WSDL\RelatedInformation.wsdl'.
Could not find file 'C:\Users\crm.users\Desktop\xxxcrm\crmtkit\CRMToolkit\Setup\WSDL\WSDL\RelatedInformation.wsdl'
Its saying RelatedInformation.wsdl is not found - and its not creating automatically inside the folder - please guide where i went wrong

Regards,
Rajesh
rajesh.ravi@gsr-inc.com
