### ISSUE TITLE
Cannot build CRM_Perf_Toolkit out of box: missing definitions

### ISSUE THREAD

**Issue by devoredevelops** [Microsoft/CRM-Performance-Toolkit#26]
EDIT: Please ignore this issue. My problem with setting up the CRM Performance Toolkit has been a result of me referencing the CRM 2013 SDK rather than the CRM 2015 SDK. Protip: even if you want to target a CRM 2013 deployment, you should reference the CRM 2015 SDK for the PowerShell script.

I have been trying to get the CRM Performance Toolkit to compile so that I can run it against a server running CRM 2016. Despite following the the instructions included with the solution, I have been unable to build the project out of box. Here are the steps I've been following:

Downloaded and installed Dynamics CRM 365 SDK.
Downloaded and installed Windows Identity Foundation SDK V3.5.
Verified that .NET Framework 4.5.2 is installed.
Downloaded and installed .NET Framework 4.5.2 Developer Pack.
Downloaded and installed Microsoft Exchange Web Services Managed API.
Downloaded and installed Microsoft Dynamics CRM Client 2016.
Unzipped contents of CRMToolkit.zip to designated folder on local D: drive in "development" folder (D:\development\).
Ran PowerShell script in D:\development\CRMToolkit\Setup with following command (usernames, passwords, and server names obfuscated with '****' for security reasons):

.\ToolkitSetup.ps1 -adminName **** -adminPassword **** -domainName dev -crmServerName **** -sqlServerName **** -orgName **** -configSku Onprem -release CRM2015SP1 -crmSdkBinDir "D:\CRM2016SDK\SDK\Bin" -crmSDKReservedDllPath "D:\Program Files\Microsoft Dynamics CRM\CRMWeb\bin" -ssl $false

While the script successfully downloads the various WSDLs and copies over necessary DLLs, it fails to build the solution. I open up the solution in Visual Studio 2015 Enterprise to numerous errors and warnings.

I'm able to resolve one of the missing assembly references "Microsoft.Exchange.WebServices" by opening the Reference Manager for the project CRM_Perf_BenchMark and browsing for the DLL file on this path: "C:\Program Files\Microsoft\Exchange\Web Services\2.0\Microsoft.Exchange.WebServices.dll". After cleaning and building again, there are still 8 errros (and 118 Warnings). They are listed here, copied with column headers, from Visual Studio:

Severity	Code	Description	Project	File	Line
Error	CS0006	Metadata file 'D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\bin\CRM2015SP1\CRM_Perf_BenchMark.dll' could not be found	Outlook_Perf_Benchmark	D:\development\CRMToolkit\CRM_Perf_Toolkit\Outlook_Perf_Benchmark\CSC	1
Error	CS0006	Metadata file 'D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\bin\CRM2015SP1\CRM_Perf_BenchMark.dll' could not be found	EMDBLoader	D:\development\CRMToolkit\CRM_Perf_Toolkit\EMDBLoader\CSC	1
Error	CS1061	'NavigateToNextEntityRequest' does not contain a definition for 'NewActiveStageId' and no extension method 'NewActiveStageId' accepting a first argument of type 'NavigateToNextEntityRequest' could be found (are you missing a using directive or an assembly reference?)	CRM_Perf_BenchMark	D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\UnitTests\GeneralUnitTests\NavigateBusinessProcessFlowUnitTest.cs	60
Error	CS1061	'NavigateToNextEntityRequest' does not contain a definition for 'NewTraversedPath' and no extension method 'NewTraversedPath' accepting a first argument of type 'NavigateToNextEntityRequest' could be found (are you missing a using directive or an assembly reference?)	CRM_Perf_BenchMark	D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\UnitTests\GeneralUnitTests\NavigateBusinessProcessFlowUnitTest.cs	61
Error	CS0246	The type or namespace name 'AddDynamicPropertyRequest' could not be found (are you missing a using directive or an assembly reference?)	DbPopulator	D:\development\CRMToolkit\CRM_Perf_Toolkit\dbPopulator\CrmEntityTemplate.cs	2548
Error	CS0246	The type or namespace name 'AddDynamicPropertyRequest' could not be found (are you missing a using directive or an assembly reference?)	DbPopulator	D:\development\CRMToolkit\CRM_Perf_Toolkit\dbPopulator\CrmEntityTemplate.cs	2548
Error	CS0246	The type or namespace name 'AddDynamicPropertyResponse' could not be found (are you missing a using directive or an assembly reference?)	DbPopulator	D:\development\CRMToolkit\CRM_Perf_Toolkit\dbPopulator\CrmEntityTemplate.cs	2553
Error	CS0246	The type or namespace name 'AddDynamicPropertyResponse' could not be found (are you missing a using directive or an assembly reference?)	DbPopulator	D:\development\CRMToolkit\CRM_Perf_Toolkit\dbPopulator\CrmEntityTemplate.cs	2553

I'm including two screenshots of Visual Studio opened to some of these errors to give you an idea of the issues I'm dealing with. I would highly appreciate anyone providing ideas of what I can do about this. Thanks!

![crnperftoolkitwontbuild1](https://cloud.githubusercontent.com/assets/8170989/21783126/b172f7a4-d67b-11e6-85d2-dd6af816f2db.png)
![crnperftoolkitwontbuild2](https://cloud.githubusercontent.com/assets/8170989/21783132/b561dc68-d67b-11e6-8496-e80183c76893.png)

**Comment by jeffreyzhzhang** [comment]
Hi Jason,

Please note the CRM Performance Toolkit on Gitub supports CRM version up to CRM2015SP1. It hasn’t been updated to support CRM2016 yet. Are you working with anyone from Microsoft at the moment? If so, you can ask to get a private copy of the toolkit for CRM2016.

Regards,
Jeffrey

**Comment by devoredevelops** [comment]
Thanks for replying, Jeffrey. While I mentioned trying to target a CRM 2016 server, I'm more interested in setting up the toolkit to work with CRM2013SP1 servers on premise. I just tried to target one of our servers which runs CRM 2016 to see if I got a different result. Either way, the VS solution itself references classes and properties which don't exist (according to Visual Studio).

I ran the PowerShell script with the following commands (certail fields masked for security, again):
.\ToolkitSetup.ps1 -adminName **** -adminPassword **** -domainName dev -crmServerName **** -sqlServerName **** -orgName **** -configSku Onprem -release CRM2013SP1 -crmSdkBinDir "D:\CRMSDK2013\Bin" -crmSDKReservedDllPath "D:\Program Files\Microsoft Dynamics CRM\CRMWeb\bin" -ssl $false

The solution failed to build. Upon opening the solution in Visual Studio 2015, I had to resolve some missing references: Microsoft.Crm.Application.Outlook.Components.Platform.dll and Microsoft.Crm.Application.Outlook.OfflineSync.dll in VS project Outlook_Perf_Benchmark
by finding DLLs in this folder: "D:\Install Files\CRM 2013\Client\i386\PFiles\MSCRM\Client\res\web\bin" (left over from an install of CRM for Outlook 2013).

I have 31 errors and 7 warnings  when trying to build with solution configuration CRM2013SP1:

Severity	Code	Description	Project	File	Line
Error	CS0246	The type or namespace name 'ExecuteTransactionRequest' could not be found (are you missing a using directive or an assembly reference?)	CRM_Perf_BenchMark	D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\UnitTests\GeneralUnitTests\ExecuteTransactionUnitTest.cs	173
Error	CS0006	Metadata file 'D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\bin\CRM2013SP1\CRM_Perf_BenchMark.dll' could not be found	EMDBLoader	D:\development\CRMToolkit\CRM_Perf_Toolkit\EMDBLoader\CSC	1
Error	CS0006	Metadata file 'D:\development\CRMToolkit\CRM_Perf_Toolkit\CreateCustomization\bin\Debug\CreateCustomization.exe' could not be found	Outlook_Perf_Benchmark	D:\development\CRMToolkit\CRM_Perf_Toolkit\Outlook_Perf_Benchmark\CSC	1
Error	CS0006	Metadata file 'D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\bin\CRM2013SP1\CRM_Perf_BenchMark.dll' could not be found	Outlook_Perf_Benchmark	D:\development\CRMToolkit\CRM_Perf_Toolkit\Outlook_Perf_Benchmark\CSC	1
Error	CS0006	Metadata file 'D:\development\CRMToolkit\CRM_Perf_Toolkit\EMDBLoader\bin\Debug\EMDBLoader.exe' could not be found	Outlook_Perf_Benchmark	D:\development\CRMToolkit\CRM_Perf_Toolkit\Outlook_Perf_Benchmark\CSC	1
Error	CS0006	Metadata file 'D:\development\CRMToolkit\CRM_Perf_Toolkit\dbPopulator\bin\Debug\NewDbPopulator.exe' could not be found	Outlook_Perf_Benchmark	D:\development\CRMToolkit\CRM_Perf_Toolkit\Outlook_Perf_Benchmark\CSC	1
Error	CS0246	The type or namespace name 'ExecuteTransactionRequest' could not be found (are you missing a using directive or an assembly reference?)	CRM_Perf_BenchMark	D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\UnitTests\GeneralUnitTests\ExecuteTransactionUnitTest.cs	359
Error	CS0246	The type or namespace name 'ExecuteTransactionRequest' could not be found (are you missing a using directive or an assembly reference?)	CRM_Perf_BenchMark	D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\UnitTests\GeneralUnitTests\ExecuteTransactionUnitTest.cs	364
Error	CS0246	The type or namespace name 'ExecuteTransactionResponse' could not be found (are you missing a using directive or an assembly reference?)	CRM_Perf_BenchMark	D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\UnitTests\GeneralUnitTests\ExecuteTransactionUnitTest.cs	365
Error	CS0246	The type or namespace name 'ExecuteTransactionRequest' could not be found (are you missing a using directive or an assembly reference?)	CRM_Perf_BenchMark	D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\UnitTests\GeneralUnitTests\ExecuteTransactionUnitTest.cs	163
Error	CS0246	The type or namespace name 'ExecuteTransactionRequest' could not be found (are you missing a using directive or an assembly reference?)	CRM_Perf_BenchMark	D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\UnitTests\GeneralUnitTests\ExecuteTransactionUnitTest.cs	175
Error	CS0246	The type or namespace name 'ExecuteTransactionRequest' could not be found (are you missing a using directive or an assembly reference?)	CRM_Perf_BenchMark	D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\UnitTests\GeneralUnitTests\ExecuteTransactionUnitTest.cs	175
Error	CS0246	The type or namespace name 'ExecuteTransactionResponse' could not be found (are you missing a using directive or an assembly reference?)	CRM_Perf_BenchMark	D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\UnitTests\GeneralUnitTests\ExecuteTransactionUnitTest.cs	282
Error	CS0246	The type or namespace name 'ExecuteTransactionFault' could not be found (are you missing a using directive or an assembly reference?)	CRM_Perf_BenchMark	D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\UnitTests\GeneralUnitTests\ExecuteTransactionUnitTest.cs	299
Error	CS0246	The type or namespace name 'ExecuteTransactionFault' could not be found (are you missing a using directive or an assembly reference?)	CRM_Perf_BenchMark	D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\UnitTests\GeneralUnitTests\ExecuteTransactionUnitTest.cs	299
Error	CS0117	'DateTimeAttributeMetadata' does not contain a definition for 'FormulaDefinition'	CreateCustomization	D:\development\CRMToolkit\CRM_Perf_Toolkit\CreateCustomization\CreateEntityOrAttribute.cs	28
Error	CS0117	'DateTimeAttributeMetadata' does not contain a definition for 'SourceType'	CreateCustomization	D:\development\CRMToolkit\CRM_Perf_Toolkit\CreateCustomization\CreateEntityOrAttribute.cs	29
Error	CS0117	'PicklistAttributeMetadata' does not contain a definition for 'FormulaDefinition'	CreateCustomization	D:\development\CRMToolkit\CRM_Perf_Toolkit\CreateCustomization\CreateEntityOrAttribute.cs	58
Error	CS0117	'PicklistAttributeMetadata' does not contain a definition for 'SourceType'	CreateCustomization	D:\development\CRMToolkit\CRM_Perf_Toolkit\CreateCustomization\CreateEntityOrAttribute.cs	59
Error	CS0117	'StringAttributeMetadata' does not contain a definition for 'SourceType'	CreateCustomization	D:\development\CRMToolkit\CRM_Perf_Toolkit\CreateCustomization\CreateEntityOrAttribute.cs	89
Error	CS0117	'MoneyAttributeMetadata' does not contain a definition for 'FormulaDefinition'	CreateCustomization	D:\development\CRMToolkit\CRM_Perf_Toolkit\CreateCustomization\CreateEntityOrAttribute.cs	118
Error	CS0117	'MoneyAttributeMetadata' does not contain a definition for 'SourceType'	CreateCustomization	D:\development\CRMToolkit\CRM_Perf_Toolkit\CreateCustomization\CreateEntityOrAttribute.cs	119
Error	CS0117	'IntegerAttributeMetadata' does not contain a definition for 'FormulaDefinition'	CreateCustomization	D:\development\CRMToolkit\CRM_Perf_Toolkit\CreateCustomization\CreateEntityOrAttribute.cs	224
Error	CS0117	'IntegerAttributeMetadata' does not contain a definition for 'SourceType'	CreateCustomization	D:\development\CRMToolkit\CRM_Perf_Toolkit\CreateCustomization\CreateEntityOrAttribute.cs	225
Error	CS0117	'OneToManyRelationshipMetadata' does not contain a definition for 'IsHierarchical'	CreateCustomization	D:\development\CRMToolkit\CRM_Perf_Toolkit\CreateCustomization\CreateEntityOrAttribute.cs	274
Error	CS0246	The type or namespace name 'AddDynamicPropertyRequest' could not be found (are you missing a using directive or an assembly reference?)	DbPopulator	D:\development\CRMToolkit\CRM_Perf_Toolkit\dbPopulator\CrmEntityTemplate.cs	2548
Error	CS0246	The type or namespace name 'AddDynamicPropertyRequest' could not be found (are you missing a using directive or an assembly reference?)	DbPopulator	D:\development\CRMToolkit\CRM_Perf_Toolkit\dbPopulator\CrmEntityTemplate.cs	2548
Error	CS0246	The type or namespace name 'AddDynamicPropertyResponse' could not be found (are you missing a using directive or an assembly reference?)	DbPopulator	D:\development\CRMToolkit\CRM_Perf_Toolkit\dbPopulator\CrmEntityTemplate.cs	2553
Error	CS0246	The type or namespace name 'AddDynamicPropertyResponse' could not be found (are you missing a using directive or an assembly reference?)	DbPopulator	D:\development\CRMToolkit\CRM_Perf_Toolkit\dbPopulator\CrmEntityTemplate.cs	2553
Error	CS0246	The type or namespace name 'PublishProductHierarchyRequest' could not be found (are you missing a using directive or an assembly reference?)	DbPopulator	D:\development\CRMToolkit\CRM_Perf_Toolkit\dbPopulator\CrmEntityTemplate.cs	3942
Error	CS0246	The type or namespace name 'PublishProductHierarchyRequest' could not be found (are you missing a using directive or an assembly reference?)	DbPopulator	D:\development\CRMToolkit\CRM_Perf_Toolkit\dbPopulator\CrmEntityTemplate.cs	3942
Warning	CS0108	'DeleteIM.user' hides inherited member 'WebTestBase.user'. Use the new keyword if hiding was intended.	CRM_Perf_BenchMark	D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\WebTests\WorkplaceWebTests\DeleteIM.cs	172
Warning	CS0108	'DeleteIM.rpcInfo' hides inherited member 'WebTestBase.rpcInfo'. Use the new keyword if hiding was intended.	CRM_Perf_BenchMark	D:\development\CRMToolkit\CRM_Perf_Toolkit\CRM_Perf_BenchMark\WebTests\WorkplaceWebTests\DeleteIM.cs	177
Warning		Load of property 'ReferencePath' failed.  Cannot add '\src\Ext\Shared\debug\amd64\Bin\' as a reference path as it is relative. Please specify an absolute path.	XrmService		
Warning		Load of property 'ReferencePath' failed.  Cannot add '..\..\..\..\..\src\Ext\Shared\debug\amd64\Bin\' as a reference path as it is relative. Please specify an absolute path.	LoadTestController		
Warning		Load of property 'ReferencePath' failed.  Cannot add '..\..\..\..\..\target\debug\amd64\' as a reference path as it is relative. Please specify an absolute path.	CRM_Perf_BenchMark		
Warning		Load of property 'ReferencePath' failed.  Cannot add '\src\Ext\Shared\debug\amd64\Bin\' as a reference path as it is relative. Please specify an absolute path.	DbPopulator		
Warning		Load of property 'ReferencePath' failed.  Cannot add '\src\Ext\Shared\debug\amd64\Bin\' as a reference path as it is relative. Please specify an absolute path.	Utility

**Comment by devoredevelops** [comment]
Great news! I got it to finally compile. The code references classes which don't exist in CRM 2013. Instead of using the CRM 2013 SDK for the DLLs necessary to build the solution, I used DLLs from the CRM 2015 SDK. I ran into a couple of snags, though: Microsoft.Crm.Sdk.Reserved.dll (at version 8) references Microsoft.Xrm.Sdk.dll (at version 7) and there was a version mismatch. I had to delete the reference to Microsoft.Xrm.Sdk in all of the projects of the solution and replace it with one from the CRM 2016 SDK. 

After I got that to resolve, I only had one error: looks like the class "PT_ClientOrgInfo" in CRM_Perf_Toolkit/Outlook_Perf_Benchmark/OfflineSyncTestDriver/BCPTransferDataProvider2.cs did not have an implementation of method "TryGetOrganizationId()" in an inherited interface "IClientOrganizationInfoEx". I solved that by copying the code from the property "OrganizationId" and made my own implementation like so:

```
public Guid TryGetOrganizationId()
{	
	string registryKeyPath = string.Format(CultureInfo.InvariantCulture, @"{0}", regloc);
	using (RegistryKey regKey = Registry.CurrentUser.OpenSubKey(registryKeyPath, true))
	{
		Exceptions.ThrowIfNull(regKey, "OrganizationDataProvider.RegistryKey");
		return new Guid((string)regKey.GetValue("OrgId"));
	};
}
```

I hope the web and unit tests will work once I get the toolkit up and running. I have more setup to do but I'm feeling positive about this. Perhaps my struggle will help someone else who has had similar issues. Thanks, Jeffrey!

**Comment by devoredevelops** [comment]
EDIT: Please ignore this issue. My problem with setting up the CRM Performance Toolkit has been a result of me referencing the CRM 2013 SDK rather than the CRM 2015 SDK. Protip: even if you want to target a CRM 2013 deployment, you should reference the CRM 2015 SDK for the PowerShell script.
